### PR TITLE
Delete sign fix

### LINKED ISSUE #4: Do not allow user to leave only a sign as an input for an expression to be calculated
Users should not be allowed to submit only a sign as a value for the expression to be calculated.
Steps to reproduce:

1 - Use 10 as input in the calculator
2 - Click the subtraction sign button
3 - Use 15 as the second input
4 - Click the equals button
5 - You will get -5 as a result
6 - Click on the DEL button to delete the digit 5, leaving only the minus sign
7 - Click again on the subtraction sign button
Actual outcome: the application allows the user to submit the operator and add the second value to be subtracted. "NaN" is shown on the screen afterwards. (Attempted invalid expression: - - 7 = NaN)
Expected outcome: User is not allowed to delete only a digit if it's a signed number, i.e the whole -5 number must be deleted, not only 5 which leaves - still on the screen.

### PR DESCRIPTION
**Pull request by jesslourenco**

### CODE REVIEW

File: calculator.js [hunk 1]
```diff
@@ -93,16 +92,20 @@ function handleButtonClick(value){
...
             return;
-        }
-
+        } 
     }     
 }
 
 function getTypeOfValue(value){
-    const operators = ['x', '/', '+', '-'];
+    const operators = ['x', '/', '+', '-'];
```
Comment (shankarnakai) [inline calculator.js:100]: This is very nitpicking, but be careful to don't add unwanted space.

File: calculator.js [hunk 2]
```diff
@@ -93,16 +92,20 @@ function handleButtonClick(value){
...
 }
 
 function getTypeOfValue(value){
-    const operators = ['x', '/', '+', '-'];
+    const operators = ['x', '/', '+', '-'];        
 
     if (Number.isInteger(parseInt(value)) === true){
-        return 'NUMBER'
+        if (digitsOnScreen.innerHTML.length > 12 && !operator){
+            console.log("Max digits reached")
```
Comment (shankarnakai) [inline calculator.js:104]: It's preferable to throw an error. 
But for it you will need to create a custom error type and capture it in the `handleButtonClick`.

Example:
```javascript
class MaxDigitError extends Error {
  constructor(number) {
    super('Max digits reached ' + number);
    this.number = number;
    this.name = "MaxDigitError";
  }
}

function getTypeOfValue(value) {
    const operators = ['x', '/', '+', '-'];
    if (Number.isInteger(parseInt(value)) === true) {
        if (digitsOnScreen.innerHTML.length > 12 && !operator) {
            throw new MaxDigitError(digitsOnScreen.innerHTML);
        }
         return 'NUMBER';
    } 
    // All the remaining code here
}


function handleButtonClick(value) {
  try {
    // Your code here
  } catch(err) {
      if (err instanceof MaxDigitError) {
        alert("Max Digit Reached");
        return;
      } else {
         replaceOnScreen(text);
         setTimeout( () => { clearScreen();}, 1000);
         return;
      }
  }
}

```

**Review by shankarnakai — APPROVED** [review]
